project:
  type: website

website:
  title: "StepuP Newsletter"
  # cookie-consent: true
  search: 
    location: navbar
    type: textbox
  navbar:
    background: primary
    pinned: true
    left:
      - text: Über StepuP
        href: about.qmd
      - text: November 2023 
        href: november23.qmd
      - text: January 2024
        href: january24.qmd

    right:
    - icon: envelope
      aria-label: email
      href: "mailto:j.welzel@neurologie.uni-kiel.de"

  page-footer: 
    left: "Copyright 2023, Julius Welzel" 


format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    fontsize: 1.2em